### PR TITLE
Requirespenpaper field (#720)

### PR DESCRIPTION
**Pull request by ezittel**
image

### CODE REVIEW

**Comment by ezittel** [comment]
https://github.com/ExpeditionRPG/expedition-app/issues/720

**Comment by toddmedema** [comment]
I suspect you'll also need to update QDL here using the same technique (latest git hash to package.json -> `npm install`)

Can you confirm that:
- This setting persists across refreshing the page
- That privately publishing it with your local copy of the Quest Creator shows up as expected in your app under Tools -> Private Quests

**Comment by ezittel** [comment]
Not sure my email answers are coming back:
I can confirm that the setting persists across refresh.

I **can't** confirm that a publish shows up in the app.  Even though I'm logging in I get a 500 error (likely auth I didn't set up correctly) when I try to publish from a locally running QC app.

**Comment by toddmedema** [comment]
To clarify, you're running the quest creator with just a normal `npm run dev`? That should point to beta api server / you shouldn't need to do anything with auth. Can you try again and I'll check the server logs to see what the error is?

**Comment by ezittel** [comment]
Taking a crack at the QDL update as well.

**Comment by ezittel** [comment]
Yes npm run dev, however the build seems to be currently broken and I can't get anything to run.  This happens in master as well.

One error:
asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 25 errors             Hash: bea7df77675df2e1d21d
Version: webpack 3.11.0
Time: 22047ms
 9 assets
  [42] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
 [360] (webpack)-dev-server/client?http://0.0.0.0:8080 7.93 kB {0} {1} [built]
[1168] ./node_modules/style-loader/addStyles.js 6.91 kB {0} [built]
[1171] multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack-dev-server/client?http://localhost:8080 ./app/React.tsx ./app/Style.scss ./node_modules/expedition-app/app/Style.scss 76 bytes {0} [built]
[1172] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
[1173] ./app/React.tsx 7.61 kB {0} [built]
[1467] ./app/components/MainContainer.tsx 2.35 kB {0} [built]
[1756] ./app/Theme.tsx 2.45 kB {0} [built]
[1757] ./node_modules/material-ui/styles/MuiThemeProvider.js 2.14 kB {0} [built]
[1771] ./node_modules/typo-js/typo.js 24.6 kB {0} [built]
[1773] ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js 1.04 kB {0} [built]
[1779] ./app/Style.scss 1.03 kB {0} [built]
[1784] ./node_modules/expedition-app/app/Style.scss 958 bytes {0} [built]
[1789] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./app/playtest/PlaytestWorker.tsx 40 bytes {1} [built]
[1790] ./app/playtest/PlaytestWorker.tsx 6.52 kB {1} [built]
    + 1782 hidden modules

ERROR in [at-loader] ./app/components/ContextEditor.tsx:64:34
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:53:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:58:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:63:11
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:49:5
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:65:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:90:17
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MenuItem> & Readonly<{ children?: ReactNode; }> & ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:98:35
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:100:76
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:101:69
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:102:36
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:107:13
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:112:15
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:28:19
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:34:19
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:55:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/Splash.tsx:117:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/Splash.tsx:120:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/base/Checkbox.tsx:17:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./node_modules/expedition-app/app/Multiplayer.tsx:417:5
    TS2322: Type '({ dispatch, getState }: MiddlewareAPI<any, any>) => (next: Dispatch<any>) => (action: any) => any' is not assignable to type 'Middleware<{}, any, Dispatch<AnyAction>>'.
  Type '(next: Dispatch<any>) => (action: any) => any' is not assignable to type '(next: Dispatch<AnyAction>) => (action: any) => any'.
    Types of parameters 'next' and 'next' are incompatible.
      Types of parameters 'action' and 'action' are incompatible.
        Type 'T' is not assignable to type 'AnyAction'.

ERROR in [at-loader] ./node_modules/expedition-app/app/actions/Web.tsx:170:6
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/SearchContainer.tsx:28:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/ToolsContainer.tsx:31:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/ToolsContainer.tsx:49:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/quest/QuestEndContainer.tsx:53:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.
webpack: Failed to compile.
Terminate batch job (Y/N)? y

C:\Users\barney-roam\expedition-quest-creator>git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

C:\Users\barney-roam\expedition-quest-creator>npm run dev

> expedition-quest-creator@1.6.7 dev C:\Users\barney-roam\expedition-quest-creator
> webpack-dev-server --progress

 10% building modules 2/2 modules 0 active
Project is running at http://0.0.0.0:8080/
webpack output is served from /
Content not from webpack is served from C:\Users\barney-roam\expedition-quest-creator\app
404s will fallback to /index.html      11% building modules 9/14 modules 5 active ...modules\expedition-app\app\Style.scss
[at-loader] Using typescript@2.8.3 from typescript and "tsconfig.json" from C:\Users\barney-roam\expedition-quest-creator/tsconfig.json.                     94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 25 errors             Hash: 6fad94f293b16b1dd735
Version: webpack 3.11.0
Time: 21364ms
 9 assets
  [42] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
 [360] (webpack)-dev-server/client?http://0.0.0.0:8080 7.93 kB {0} {1} [built]
[1168] ./node_modules/style-loader/addStyles.js 6.91 kB {0} [built]
[1171] multi (webpack)-dev-server/client?http://0.0.0.0:8080 webpack-dev-server/client?http://localhost:8080 ./app/React.tsx ./app/Style.scss ./node_modules/expedition-app/app/Style.scss 76 bytes {0} [built]
[1172] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
[1173] ./app/React.tsx 7.61 kB {0} [built]
[1467] ./app/components/MainContainer.tsx 2.35 kB {0} [built]
[1756] ./app/Theme.tsx 2.45 kB {0} [built]
[1757] ./node_modules/material-ui/styles/MuiThemeProvider.js 2.14 kB {0} [built]
[1771] ./node_modules/typo-js/typo.js 24.6 kB {0} [built]
[1773] ./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js 1.04 kB {0} [built]
[1779] ./app/Style.scss 1.03 kB {0} [built]
[1784] ./node_modules/expedition-app/app/Style.scss 958 bytes {0} [built]
[1789] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./app/playtest/PlaytestWorker.tsx 40 bytes {1} [built]
[1790] ./app/playtest/PlaytestWorker.tsx 6.52 kB {1} [built]
    + 1782 hidden modules

ERROR in [at-loader] ./app/components/ContextEditor.tsx:64:34
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:53:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:58:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Main.tsx:63:11
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:49:5
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:65:9
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:90:17
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<MenuItem> & Readonly<{ children?: ReactNode; }> & ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:98:35
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:100:76
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:101:69
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:102:36
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:107:13
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/QuestAppBar.tsx:112:15
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:28:19
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:34:19
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./app/components/Splash.tsx:55:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/Splash.tsx:117:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/Splash.tsx:120:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ExpeditionButton> & Readonly<{ children?: ReactNod...'.

ERROR in [at-loader] ./app/components/base/Checkbox.tsx:17:21
    TS2339: Property 'onTouchTap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FlatButton> & Readonly<{ children?: ReactNode; }> ...'.

ERROR in [at-loader] ./node_modules/expedition-app/app/Multiplayer.tsx:417:5
    TS2322: Type '({ dispatch, getState }: MiddlewareAPI<any, any>) => (next: Dispatch<any>) => (action: any) => any' is not assignable to type 'Middleware<{}, any, Dispatch<AnyAction>>'.
  Type '(next: Dispatch<any>) => (action: any) => any' is not assignable to type '(next: Dispatch<AnyAction>) => (action: any) => any'.
    Types of parameters 'next' and 'next' are incompatible.
      Types of parameters 'action' and 'action' are incompatible.
        Type 'T' is not assignable to type 'AnyAction'.

ERROR in [at-loader] ./node_modules/expedition-app/app/actions/Web.tsx:170:6
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/SearchContainer.tsx:28:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/ToolsContainer.tsx:31:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/ToolsContainer.tsx:49:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.

ERROR in [at-loader] ./node_modules/expedition-app/app/components/views/quest/QuestEndContainer.tsx:53:10
    TS2339: Property 'then' does not exist on type '(dispatch: Dispatch<any>, getState: () => AppState) => Promise<UserState>'.
webpack: Failed to compile.


> To clarify, you're running the quest creator with just a normal npm run dev? That should point to beta api server / you shouldn't need to do anything with auth. Can you try again and I'll check the server logs to see what the error is?

**Comment by toddmedema** [comment]
Hmm, lots of weird typing errors generally point to a wrong version of a dependency. Can you delete your node_modules folder and try re-running `npm install`?

**Comment by ezittel** [comment]
same result after npm install

**Comment by toddmedema** [comment]
Ooooh. Ok, I know what's going on. You'll need to revert your change to the app git hash and re-install your modules. We just did a huge upgrade to the app to the new version of React + Typescript, and have yet to update the Quest Creator to be compatible. Thankfully, you don't need the latest version of the app for this to work in the Quest Creator :)

**Comment by ezittel** [comment]
okay that did it.  I just tried a private publish again and got the error 500.  So about 10:28 ET.

**Comment by ezittel** [comment]
It is actually saving, it's just giving me an error.  I can confirm that the setting does not persist when I bring up the saved version, so I'll have to figure out where I missed.

**Comment by ezittel** [comment]
How do I get this saved quest to show up in the app?  Either the production app or the one running on local?  If I save and then go back to publish (and stay local without trying to bring it up from the google drive) then the setting does persist.

**Comment by ezittel** [comment]
This might be okay as well - could use a review.

**Comment by ezittel** [comment]
This part is an issue - I can see it in google drive, however.  I don't see it in the app.

>That privately publishing it with your local copy of the Quest Creator shows up as expected in your app under Tools -> Private Quests

**Comment by ezittel** [comment]
It does the same thing in the master branch.  Even if I log out and back in I get the error 500 while publishing and it tells me I'm nog logged in.  It writes to the drive just fine though.

**Pull request merged**
